Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20210415.0.0"
  config.vm.hostname = "pod-davidwah-node01"
  config.vm.network "private_network", ip:"10.10.10.10"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
end
